# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr
  
script: 
  - |
    travis_wait 20 R CMD build .
    travis_wait 20 R CMD check tidyjson*tar.gz

after_success:
  - Rscript -e 'library(covr); codecov()'

after_script:
 - ./travis-tool.sh dump_logs
